MAHARASHTRA_DISTRICT_TO_IMD_SUBDIVISION = {
    "mumbai city": "Konkan & Goa",
    "mumbai suburban": "Konkan & Goa",
    "palghar": "Konkan & Goa",
    "thane": "Konkan & Goa",
    "raigad": "Konkan & Goa",
    "raigadh": "Konkan & Goa",
    "ratnagiri": "Konkan & Goa",
    "sindhudurg": "Konkan & Goa",
    "nandurbar": "Madhya Maharashtra",
    "dhule": "Madhya Maharashtra",
    "jalgaon": "Madhya Maharashtra",
    "nashik": "Madhya Maharashtra",
    "ahmednagar": "Madhya Maharashtra",
    "ahilyanagar": "Madhya Maharashtra",
    "pune": "Madhya Maharashtra",
    "satara": "Madhya Maharashtra",
    "sangli": "Madhya Maharashtra",
    "solapur": "Madhya Maharashtra",
    "kolhapur": "Madhya Maharashtra",
    "chhatrapati sambhajinagar": "Marathwada",
    "aurangabad": "Marathwada",
    "jalna": "Marathwada",
    "beed": "Marathwada",
    "bid": "Marathwada",
    "latur": "Marathwada",
    "dharashiv": "Marathwada",
    "osmanabad": "Marathwada",
    "nanded": "Marathwada",
    "parbhani": "Marathwada",
    "hingoli": "Marathwada",
    "buldhana": "Vidarbha",
    "akola": "Vidarbha",
    "washim": "Vidarbha",
    "amravati": "Vidarbha",
    "yavatmal": "Vidarbha",
    "wardha": "Vidarbha",
    "nagpur": "Vidarbha",
    "bhandara": "Vidarbha",
    "gondia": "Vidarbha",
    "chandrapur": "Vidarbha",
    "gadchiroli": "Vidarbha",
}


def maharashtra_imd_subdivision_for_district(district: str) -> str | None:
    return MAHARASHTRA_DISTRICT_TO_IMD_SUBDIVISION.get(" ".join(district.lower().split()))
